### ISSUE TITLE
Proposal to allow multi-user installations

### ISSUE THREAD

**Issue by omsai** [lgcrego/Dynemol#7]
Currently DynEMol makes the assumption that certain files are in the current working directory such as `env.sh`, various `*.dat` files, etc.

I was wondering if you folks would be interested in allowing multiple users to use DynEMol from a read-only shared installation directory without each user having to compile and install DynEMol?

The reason I ask is I have been trying to make it easy for anyone to compile and install DynEMol from source using Lawrence Livermore's [spack](https://spack.io) project.  The project will automatically compile and install all dependencies from source and allows multiple versions to be installed concurrently.  This makes it possible for HPC users to not have to rely on their administrators to compile software, create module files, etc:

```console
$ spack spec dynemol  # show associated dependencies intel-mkl and intel-mpi
Input spec
--------------------------------
dynemol

Concretized
--------------------------------
dynemol@18d7aa2fcc5b9af174af1a5e313644ac3c77bf6b%intel@16.1~cuda arch=linux-rhel6-x86_64
    ^intel-mkl@16.1%intel@16.1+ilp64+shared threads=openmp arch=linux-rhel6-x86_64
    ^intel-mpi@16.1%intel@16.1 arch=linux-rhel6-x86_64
```

## Current behavior

So far I have created the installation package, but because DynEMol directly tries to run `./env.sh` ouside of the source directory, it fails:

```console
$ spack load dynemol  # load the installed dynemol package
$ dynemol             # run dynemol
Using only CPU
sh: ./env.sh: No such file or directory
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 3, file /shared/admin/sw-src/rhel6/dynemol/18d7aa2/spack/my_eht_parameters.dat
Image              PC                Routine            Line        Source             
dynemol            00000000006B69C9  Unknown               Unknown  Unknown
dynemol            00000000006CCF12  Unknown               Unknown  Unknown
dynemol            00000000004B1BB3  Unknown               Unknown  Unknown
dynemol            000000000069F15A  Unknown               Unknown  Unknown
dynemol            0000000000405D5E  Unknown               Unknown  Unknown
libc.so.6          00000037A861ED1D  Unknown               Unknown  Unknown
dynemol            0000000000405BE9  Unknown               Unknown  Unknown
```

The `makefile` has no install rule, so I manually create the installation prefix,  What I need your help with is understanding the purpose of all associated data files and scripts.  As far as I can tell, these are the non-source files:

```console
$ find -type f -not -iregex '.*\(f\|f90\|cu\|inc\|cpp\|[.]h\|makefile\|[.]fi\|[.]bsh\|[.]md\|gitignore\)$' -exec file {} + | sort
./atomic_mass.dat:              ASCII text
./casida-input.dat:             ASCII text
./env.sh:                       Bourne-Again shell script text executable
./input-GA.dat:                 ASCII text
./IO_file_formats:              ASCII text
./IO_file_MM-formats:           UTF-8 Unicode English text
./my_eht_parameters.dat:        FORTRAN program
./opt_eht_parameters.input.dat: FORTRAN program
./script-vmd:                   ASCII text
```

## Proposed solution

Based on my limited understanding of what the input files are and what the read-only reference files are, following the recommendations of `man 7 hier` maybe the installation directory should look something like this?

```console
$ spack cd --install-dir dynemol
$ tree -F
.
├── bin/
│   ├── dynemol*
│   └── dynemol_setup*  # renamed from env.sh
└── share/
    ├── doc/
    │   └── dynemol/
    │       ├── manual.pdf
    │       └── README.md
    └── dynemol/
        ├── data/  # read-only files needed by dynemol
        │   ├── atomic_mass.dat
        │   ├── IO_file_formats
        │   └── IO_file_MM-formats
        └── input/  # writable files to be coped to the user's current working directory
            ├── casida-input.dat
            ├── input-GA.dat
            ├── my_eht_parameters.dat
            ├── opt_eht_parameters.input.dat
            └── script-vmd

7 directories, 12 files
```

Are my guesses of what the `input/` files are that should be in the user's directory correct and the `data/` read-only files for DynEMol correct?

Note that the `env.sh` file has been renamed to `dynemol_setup` so that it can be run globally.  If DynEMol has a missing file it could say "run dynemol_setup to create input files".

## Spack files

Here is the spack package script I have been working on:
https://github.com/UConn-HPC/spack/blob/bcbdf86136910dc089f4c3794de730496d5e2550/var/spack/repos/builtin/packages/dynemol/package.py

To fully reproduce the setup you could run:

```bash
git clone https://github.com/UConn-HPC/spack.git -b package/dynemol
source spack/share/spack/setup-env.sh
# Create the spack.yaml file in this directory from the file below, edit paths to Intel compiler
spack concretize --force
spack install --verbose dynemol
spack load dynemol
dynemol
spack cd --install-dir dynemol
tree -F
```

Here is my `spack.yaml` environment file:

```yaml
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  specs: [dynemol]
  view: false
  packages:
    intel-mkl:
      buildable: false
      paths:
        intel-mkl@16.1 +ilp64 threads=openmp: /apps2/intelics/2016.1-full-gcc/parallel_studio_xe_2016.1.056/compilers_and_libraries_2016/linux
    intel-mpi:
      buildable: false
      paths:
        intel-mpi@16.1: /apps2/intelics/2016.1-full-gcc/parallel_studio_xe_2016.1.056/compilers_and_libraries_2016/linux/mpi
    all:
      compiler: [intel@16.1]
      providers:
        blas: [intel-mkl]
        lapack: [intel-mkl]
        mkl: [intel-mkl]
        mpi: [intel-mpi]
  compilers:
  - compiler:
      operating_system: rhel6
      paths:
        cc: /apps2/intelics/2016.1-full-gcc/bin/icc
        cxx: /apps2/intelics/2016.1-full-gcc/bin/icpc
        f77: /apps2/intelics/2016.1-full-gcc/bin/ifort
        fc: /apps2/intelics/2016.1-full-gcc/bin/ifort
      spec: intel@16.1
      target: x86_64
      modules: []
```

The installation with `--verbose` turned off should look similar to this;

```
$ spack install dynemol
==> intel-mkl@16.1 : externally installed in /apps2/intelics/2016.1-full-gcc/parallel_studio_xe_2016.1.056/compilers_and_libraries_2016/linux
==> intel-mkl@16.1 : already registered in DB
==> intel-mpi@16.1 : externally installed in /apps2/intelics/2016.1-full-gcc/parallel_studio_xe_2016.1.056/compilers_and_libraries_2016/linux/mpi
==> intel-mpi@16.1 : already registered in DB
==> Installing dynemol      
==> Searching for binary cache of dynemol
==> Warning: No Spack mirrors are currently configured
==> No binary for dynemol found: installing from source
==> Using cached archive: /shared/admin/sw-src/rhel6/dynemol/18d7aa2/spack/var/spack/cache/dynemol/dynemol-18d7aa2fcc5b9af174af1a5e313644ac3c77bf6b
.tar.gz                
==> Staging archive: /shared/admin/sw-src/rhel6/dynemol/18d7aa2/spack/var/spack/stage/dynemol-18d7aa2fcc5b9af174af1a5e313644ac3c77bf6b-mf3lejctlhre
stvuhlzgnyuvvcdd4hs4/18d7aa2fcc5b9af174af1a5e313644ac3c77bf6b
==> Created stage in /shared/admin/sw-src/rhel6/dynemol/18d7aa2/spack/var/spack/stage/dynemol-18d7aa2fcc5b9af174af1a5e313644ac3c77bf6b-mf3lejctlhre
stvuhlzgnyuvvcdd4hs4
==> Ran patch() for dynemol
==> Building dynemol [MakefilePackage]
==> Executing phase: 'edit'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed dynemol
  Fetch: 0.13s.  Build: 3m 24.68s.  Total: 3m 24.81s.
[+] /shared/admin/sw-src/rhel6/dynemol/18d7aa2/spack/opt/spack/linux-rhel6-x86_64/intel-16.1/dynemol-18d7aa2fcc5b9af174af1a5e313644ac3c77bf6b-mf3le
jctlhrestvuhlzgnyuvvcdd4hs4
```
